import type { Metadata } from 'next'
import { storyblokInit, apiPlugin } from '@storyblok/react/rsc'

import { COMPONENTS } from '@/components/sb'
import StoryblokProvider from '@/components/sb/StoryBlokProvider'
import { Inter } from 'next/font/google'
import './globals.css'

storyblokInit({
  accessToken: process.env.NEXT_PUBLIC_SB_PREVIEW_TOKEN,
  use: [apiPlugin],
  components: COMPONENTS,
  apiOptions: {
    region: 'eu',
  },
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Next.js StoryBlok template',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoryblokProvider>{children}</StoryblokProvider>
      </body>
    </html>
  )
}
